# Neden NumPy ?

In [6]:
a = [1,2,3,4]
b = [2,3,4,5]

In [8]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i] * b[i])
    
ab

[2, 6, 12, 20]

In [9]:
import numpy as np

In [10]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [11]:
a * b

array([ 2,  6, 12, 20])

In [14]:
type(a)

numpy.ndarray

## NumPy Array'i Oluşturma

In [1]:
import numpy as np

In [17]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [18]:
a = np.array([1,2,3,4,5])

In [19]:
type(a)

numpy.ndarray

In [21]:
np.array([3.14, 4, 2, 13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [22]:
np.array([3.14, 4, 2, 13], dtype = "int32")

array([ 3,  4,  2, 13])

#### Sıfırdan Array Oluşturma

In [35]:
# 10 tane sıfırdan oluşan array oluşturduk
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
# 3x5 boyunda 1'lerden oluşan array oluşturduk
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
# Sadece belli bir sayıda array oluşturmak için full() fonksiyonu kullanılır
np.full((3,3), 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [39]:
# Doğrusal bir array oluşturmak, 0'dan 31'e kadar üçer üçer artan dizi
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [40]:
# İki değer arasında belirli bir sayıda değer oluşturma, 0 ile 1 arasında 10 tane değer oluşurduk -> linspace
np.linspace(0,1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [42]:
# Normal dağılım, ortalaması 10, std 4 olan 3x4 boyudunda matris
np.random.normal(10,4, (3,4))

array([[ 6.57915582, 17.39517549,  9.74704947, 18.40482578],
       [13.34427853, 11.77473767, 10.56501572,  4.664746  ],
       [11.10676181,  6.08972048,  6.89952054,  9.33275028]])

In [43]:
# int sayılardan rastgele sayılardan oluşan diz
np.random.randint(0,10, (3,3))

array([[4, 8, 3],
       [3, 5, 2],
       [0, 7, 2]])

## NumpPy Array Özellikleri

* **ndim** : boyut sayısı
* **shape** : boyut bilgisi
* **size** : toplam eleman sayısı
* **dtype** : array veri tipi 

In [2]:
import numpy as np

In [6]:
# 0 ile 10 arasında 10 tane rastgele int değer oluşturduk
np.random.randint(10, size = 10)

array([1, 4, 6, 4, 8, 1, 0, 4, 3, 2])

In [17]:
a = np.random.randint(10, size = 10)
a

array([1, 7, 8, 5, 6, 2, 2, 8, 2, 8])

In [18]:
# boyut sayısı -> tek boyutlu (vektör olduğu için sonuç 1)
a.ndim

1

In [19]:
# boyut bilgisini verdi, elimizdeki array tek boyutlu olduğu için sadece bir boyutunun bilgisi
# verilmiş ve içerisinde 10 tane eleman var denmiş
a.shape

(10,)

In [20]:
# içindeki toplam eleman sayısını verdi
a.size

10

In [21]:
a.dtype

dtype('int32')

In [22]:
b = np.random.randint(10, size = (3,5))
b

array([[7, 5, 6, 4, 6],
       [5, 8, 4, 9, 8],
       [7, 9, 4, 7, 5]])

In [24]:
# matris olduğu için 2 boyutlu sonuç 2 çıktı
b.ndim

2

In [26]:
# 3x5 boyunda
b.shape

(3, 5)

In [28]:
# toplam eleman sayısı
b.size

15

In [30]:
# içerisindeki tip
b.dtype

dtype('int32')

## Yeniden Şekillendirme (reshaping) : reshape

In [35]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
# Burada elimizde 1'den 10'a kadar oluşan rakamlardan bir array var. Amacım bu array üzerinden 
# 3x3 'lü yeni bir array oluşturmak olsun işte reshape methodu (fonksiyonu) kullanılır.
# Peki neden böyle bir şeye ihtiyacımız var, şöyleki yaptığımız çalışmalarda fonksiyonlarımızın yada 
# döngülerimizin üretmiş olduğu çıktıları tek bir boyutta tek bir array formunda gerçekleşebiliyor.
# Bunları tek boyuttan 2 boyuta, bazende 2 boyuttan tek boyuta indirmek ihtiyaçları 
# gerçekleşebiliyor. İşte bu sebeple bu yapısal dönüşümleri iyi kavramak gerekiyor.

In [39]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a.ndim

1

In [50]:
# 2 boyutlu olur ama 1 satır 9 sütundan oluşur
b = a.reshape((1,9))

In [51]:
b.ndim

2

In [62]:
# 2 boyuttan tek boyuta indirgedik

In [54]:
a = np.random.randint(1,10, size = (3,3))
a

array([[7, 5, 1],
       [5, 1, 7],
       [7, 8, 2]])

In [58]:
b = a.reshape(9)

In [59]:
b

array([7, 5, 1, 5, 1, 7, 7, 8, 2])

In [70]:
b.ndim

1

# Array Birleştirme (Concatenation)

In [71]:
import numpy as np

In [73]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [76]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [77]:
z = np.array([7,8,9])

In [78]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# 2 boyut üzerinde birleştirme

In [81]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [82]:
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [85]:
# peki ben bunları satır bazında değilde sütun bazında birleştirmek istersek ne yapıcam,
# o zamanda axis argümanını kullanıcaz, yan yana
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [88]:
array1 = np.array([[1,2,3], 
                 [4,5,6]])
array2 = np.array([[-1,-2,-3],
                 [-4,-5,-6]])

### stac ile birleştirme

In [93]:
# vstack -> dikeyde birleştirme
np.vstack((array1, array2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [-1, -2, -3],
       [-4, -5, -6]])

In [94]:
# hstack -> yatayda birleştirme
np.hstack((array1, array2))

array([[ 1,  2,  3, -1, -2, -3],
       [ 4,  5,  6, -4, -5, -6]])

# Array Ayırma (Splitting) : split

In [96]:
x = np.array([1,2,3,99,99,3,2,1])

In [97]:
# Burada [1,2,3]'ü [99,99]'u ve [3,2,1] ifadelerini ayırmak istiyorum.

In [99]:
np.split(x, [3,5])
# 0-3 , 3-4 , ve üzeri

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [100]:
a,b,c = np.split(x, [3,5])
# çıktıları a,b,c içine atar

In [101]:
a

array([1, 2, 3])

In [102]:
b

array([99, 99])

In [103]:
c

array([3, 2, 1])

In [104]:
# 2 boyutlu split ayrıma

In [106]:
m = np.arange(16).reshape((4,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
np.vsplit(m, [2])
# m'yi böl 2. indexten itibaren böl

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [115]:
ust,alt = np.vsplit(m, [2])
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [116]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
np.hsplit(m, [2])
# m'yi böl 2. sütundan itibaren böl

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [118]:
sag, sol = np.hsplit(m, [2])
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [119]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [125]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [126]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [127]:
v

array([2, 1, 4, 3, 5])

In [130]:
# bu şekilde kullanılırsa ana array'i değiştirir
v.sort()

In [129]:
v

array([1, 2, 3, 4, 5])

In [131]:
# 2 boyutlu array sıralama

In [135]:
# ortalaması 20, std 5 3x3 boyutunda bir matris
m = np.random.normal(20,5, (3,3))
m

array([[16.66832225, 21.05895371, 19.13691453],
       [18.78991754, 21.31648264, 12.84432586],
       [23.06447796, 14.85492859, 17.5057359 ]])

In [136]:
# 2 boyutlu array'in satırlarını sıralamak istiyorum

In [141]:
np.sort(m, axis = 1)

array([[16.66832225, 19.13691453, 21.05895371],
       [12.84432586, 18.78991754, 21.31648264],
       [14.85492859, 17.5057359 , 23.06447796]])

In [142]:
np.sort(m, axis = 0)

array([[16.66832225, 14.85492859, 12.84432586],
       [18.78991754, 21.05895371, 17.5057359 ],
       [23.06447796, 21.31648264, 19.13691453]])

In [145]:
np.random.randint(10 , size = (3,3,2))

array([[[2, 0],
        [6, 9],
        [6, 9]],

       [[0, 0],
        [1, 4],
        [2, 9]],

       [[2, 4],
        [7, 3],
        [9, 8]]])

# İndex ile Elemanlara Erişmek

In [2]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([6, 3, 3, 6, 8, 4, 7, 2, 6, 8])

In [3]:
a[0]

8

In [4]:
a[-1]

8

In [5]:
a[0] = 100
a

array([100,   6,   6,   7,   6,   1,   6,   1,   1,   8])

In [4]:
m = np.random.randint(10, size = (3,5))
m

array([[7, 5, 1, 8, 2],
       [9, 7, 5, 4, 0],
       [9, 6, 2, 5, 5]])

In [10]:
m[0,0]

1

In [11]:
m[1,1]

9

In [14]:
m[1,4] = 99
m

array([[ 1,  5,  2,  1,  0],
       [ 5,  9,  0,  4, 99],
       [ 4,  5,  4,  1,  7]])

In [15]:
# Numpy arrayleri için fixtype yani sabitlenmiş tipli demiştik mesela burada bir sürekli değişken yani float
# tipindeki  bir değeri bu arraye eklemeye çalışalım

In [16]:
m

array([[ 1,  5,  2,  1,  0],
       [ 5,  9,  0,  4, 99],
       [ 4,  5,  4,  1,  7]])

In [5]:
# int'a çevirir fixtype olduğu için 
m[1,0] = 2.2
m

array([[7, 5, 1, 8, 2],
       [2, 7, 5, 4, 0],
       [9, 6, 2, 5, 5]])

# Slicing ile Elemanlara Erişmek (Array Alt Küme İşlemleri)

In [6]:
import numpy as np
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
# 0. indexten 3.indexe kadar git, seç
a[0:3]

array([20, 21, 22])

In [10]:
# baştan 3. indexe kadar git, seç
a[:3]

array([20, 21, 22])

In [12]:
# 3.indexten son indexe kadar git
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [18]:
# 1.indexten başlayarak ikişer ikişer artarak seçer
a[1::2]

array([21, 23, 25, 27, 29])

In [15]:
a[::2]

array([20, 22, 24, 26, 28])

In [19]:
# 0.indexten başlar üçer üçer artarak seçer
a[0::3]

array([20, 23, 26, 29])

In [20]:
# iki boyutlu slice işlemleri

In [22]:
m = np.random.randint(10, size = (5,5))
m

array([[1, 4, 4, 8, 1],
       [1, 6, 0, 8, 6],
       [4, 5, 8, 3, 2],
       [9, 1, 5, 9, 9],
       [8, 7, 4, 3, 6]])

In [27]:
# matrisi iki bileşen olarak düşünücez satırlar ve sütunlar
# m[:,0] -> bütün satırları seç virgül 0.sütun
# bütun satırları seç ve şu sütunu seç demenin yolu budur
m[:,0]

array([1, 1, 4, 9, 8])

In [26]:
# bütün satırı seç virgül 1.indexli sütunu seç
m[:,1]

array([4, 6, 5, 1, 7])

In [48]:
# [0,:] -> 0.satır seç, tüm sütunları seç

In [28]:
m[0,:]

array([1, 4, 4, 8, 1])

In [29]:
m[0]

array([1, 4, 4, 8, 1])

In [31]:
m

array([[1, 4, 4, 8, 1],
       [1, 6, 0, 8, 6],
       [4, 5, 8, 3, 2],
       [9, 1, 5, 9, 9],
       [8, 7, 4, 3, 6]])

In [32]:
# 1.satırı seç , tüm sütunu seç
m[1,:]

array([1, 6, 0, 8, 6])

In [34]:
# 0.indexten 2.indexe kadar (0 ve 1) satırları seç , 0.indexten 3.indexe kadar sütunları seç
m[0:2 , 0:3]

array([[1, 4, 4],
       [1, 6, 0]])

In [42]:
# tüm satırları al, 0. ve 1. sütunları seç
m[:,0:2]

array([[1, 4],
       [1, 6],
       [4, 5],
       [9, 1],
       [8, 7]])

In [44]:
# 0.indexten başlar ikişer ikişer artarak seçmeye devam et
m[: , 0::2]

array([[1, 4, 1],
       [1, 0, 6],
       [4, 8, 2],
       [9, 5, 9],
       [8, 4, 6]])

In [47]:
# 1. ve 2. satırları seç, 0. ve 1. sütunları seç
m[1:3 , 0:2]

array([[1, 6],
       [4, 5]])

# Alt Küme Üzerinde İşlem Yapmak

* Örneğin bir arrayin alt kümesine eriştikten sonra bunu isimlendirip kayıt ettiğimizi düşünelim bu kayıt etmiş olduğumuz isimlendirme üzerinde bir değişiklik yaptığımızda arrayin ilk halindede değişiklik olmakta. Fakat bazen seçilen arrayin alt kümesi üzerinde o alt kümeye ait özel işlemler yapılmak istenebilir. Çok büyük boyutlu arrayler ile çalıştığımızda seçmiş olduğumuz arrayin alt kümesi üzerinde bi işlem yaptığımızda bunun ana array üzerinde değişikliğe sebep olması işimize gelebilir ama bazende ulaşmış olduğumuz alt küme üzerinde yapmış oldğumuz işlemlerin o alt kümelelere özel kalmasını isteriz işte bu durumda alt kümeleri bağımsızlaştırmak diyebileceğimiz bir işlem yapılması gerekiyor en azından bu işlemlerin farkında olunması gerekiyor hiç farkında olmadan bazı hatarlar yapmamak adına.

In [50]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[9, 7, 3, 6, 9],
       [9, 9, 7, 8, 5],
       [8, 2, 9, 4, 9],
       [5, 1, 8, 2, 2],
       [5, 5, 1, 9, 3]])

In [52]:
alt_a = a[0:3,0:2]
alt_a

array([[9, 7],
       [9, 9],
       [8, 2]])

In [58]:
alt_a[0,0] = 99999
alt_a[1,1] = 888
alt_a

array([[99999,     7],
       [    9,   888],
       [    8,     2]])

In [72]:
# Görüldüğü üzere alt kümede yapılan değişiklik ana a arrayinindede değişiklik yaptı
# bu durum bazen çok büyük boyutlu arraylerde belirli parçaları seçip onlar üzerinde çalıştığımızda ve ana
# array üzerindede değişiklik yaptığında işimize gelir fakat bazende arrayin alt kümesini seçip onun üzerinde
# işlemler yapmak isteyebiliyoruz ve bu durumun ana arrayimizi bozmamasını istiyor olabiliriz.
# bunun için copy() isimli bir method kullanıcaz.
a

array([[99999,     7,     3,     6,     9],
       [    9,   888,     7,     8,     5],
       [    8,     2,     9,     4,     9],
       [    5,     1,     8,     2,     2],
       [    5,     5,     1,     9,     3]])

In [63]:
m = np.random.randint(10, size = (5,5))
m

array([[9, 4, 6, 2, 1],
       [7, 0, 1, 4, 4],
       [6, 4, 5, 6, 8],
       [8, 3, 5, 2, 5],
       [8, 9, 1, 2, 5]])

In [65]:
# copy() metodunu yazdığımız zaman seçmiş olduğumuz alt kümeyi ana arrayden bağımsızlaştırır.
alt_b = m[0:3,0:2].copy()
alt_b

array([[9, 4],
       [7, 0],
       [6, 4]])

In [67]:
alt_b[0,0] = 9999
alt_b

array([[9999,    4],
       [   7,    0],
       [   6,    4]])

In [69]:
# görüldüğü gibi copy() methodu sayesinde oluşturdmuş olduğumuz ana arrayin yapsısında bir değişiklik olmadı
m

array([[9, 4, 6, 2, 1],
       [7, 0, 1, 4, 4],
       [6, 4, 5, 6, 8],
       [8, 3, 5, 2, 5],
       [8, 9, 1, 2, 5]])

In [70]:
alt_b * 3

array([[29997,    12],
       [   21,     0],
       [   18,    12]])

# Fancy Index ile Elemanlara Erişmek

In [2]:
import numpy as np
v = np.arange(0,30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
# örneğin biz bu arrayin 3 ve 5 nolu indexlerine erişmek isteyelim bu durumda napıyoruz
v[3]

9

In [5]:
v[5]

15

In [6]:
# bunları bir arada görmek için
[v[1], v[3], v[5]]

[3, 9, 15]

In [30]:
# elimdeki 3 tane değer için böyle bir bilgiye kolayca erişebildim fakat öyleki bir fonksiyonun çıktısı
# bir döngünün çıktısı elimde yüzlerce index bilgisi taşıyo ve ben bu index bilgilerinin her  birisinin
# elimdeki arrayin içerisinden gidip yakalamak istiyorum. Bunu nasıl yapıcam
# al_getir isminde bir liste oluşturduk ve bunu kayıt ettik. Elimizde birde v arrayi var
# v[al_getir] dediğimiz zaman istenilen indexleri getirmiş oldu, işte buna fancy index denir.
# Yani elimizdeki bir döngü yada fonksiyon onlarca belki yüzlerce değeri ürettiyse ve üretilen bu değerlerin 
# her birisini ben bu array'in içerisinden çekmek istiyorsam bu şekilde basitçe gerçekleştirebiliriz.

In [8]:
al_getir = [1,3,5]

In [9]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
v[al_getir]

array([ 3,  9, 15])

In [13]:
# iki boyutta fancy ındex işlemi

In [14]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
# iki boyutlu işlemlerde yine bir liste yada numpy arrayi oluşturabiliriz.

In [18]:
satir = np.array([0,1])
sutun = np.array([1,2])
m[satir, sutun]

array([1, 5])

In [19]:
# fancy kavramıyla slice, klasik index işlemini ve bazı işlemleri bir arada kullanabiliyoruz.
# basit index ile fancy index

In [31]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
# 0.satıda 1. ve 2.sutun
m[0, [1,2]]

array([1, 2])

In [29]:
# slice ile fancy
# 0'dan son satıra kadar git , [1.ve 2.sutunları aldı] 

In [23]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [32]:
import numpy as np
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [50]:
# belirli bir vektörün yada arrayin içerisinde belirli bir koşulu çağırıp bu koşulu sağlayan elemanların
# yakalanması işlemleri

In [35]:
# v arrayi içerisindeki değerlerin 5'ten büyük olup olmadığını sorgular
v > 5

array([False, False, False, False, False])

In [36]:
v < 3

array([ True,  True, False, False, False])

* ilk yaptığımız işlem bu şartın sağlanıp sağlanmadığı kontrol etmek oldu 
* peki şimdi bu şimdi şartı sağlayanlara nasıl erişicez, işte burada tekrar **fancy** işlemi devreye giriyor

In [39]:
# v[v < 3] -> v vöktörünün içine giriyorum ve diyorum ki ben senin içersinde şu sorgu sonucunu sağlayan
# değerleri görmek istiyorum 

In [40]:
v[v < 3]

array([1, 2])

In [41]:
v[v >  3]

array([4, 5])

In [42]:
v[v >= 3]

array([3, 4, 5])

In [43]:
v[v <= 3]

array([1, 2, 3])

In [44]:
v[v == 3]

array([3])

In [45]:
v[v != 3]

array([1, 2, 4, 5])

In [46]:
v * 2

array([ 2,  4,  6,  8, 10])

In [47]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [48]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [49]:
v ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel İşlemler

In [1]:
import numpy as np
v = np.array([1,2,3,4,5,])
v

array([1, 2, 3, 4, 5])

In [3]:
v - 1 

array([0, 1, 2, 3, 4])

In [4]:
v * 5

array([ 5, 10, 15, 20, 25])

In [5]:
v*5/10 -1 

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [8]:
# çıkarma işlemi
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [10]:
# toplama işlemi
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [12]:
# çarpma işlemi
np.multiply(v, 2)

array([ 2,  4,  6,  8, 10])

In [15]:
# bölme işlemi
np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [17]:
# üs alma
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [19]:
# v'nin 2'ye bölümünden kalanları getir -> mod alma
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [20]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [23]:
# absolute -> mutlak değer almak iç kullanılır
np.absolute(np.array([-3]))

array([3])

In [25]:
np.sin(360)

0.9589157234143065

In [26]:
np.cos(180)

-0.5984600690578581

In [27]:
v = np.array([1,2,3])

In [28]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [29]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [30]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [31]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\ygtoz\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\ygtoz\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

In [33]:
# cheatsheet -> kopya kağıdı

In [35]:
v

array([1, 2, 3])

In [37]:
# ortalama 
np.mean(v)

2.0

In [39]:
# içerisindeki değerleri toplar
np.sum(v)

6

In [40]:
np.min(v)

1

In [41]:
v.min()

1

In [42]:
v.max()

3

# NumPy ile İki Bilinmeyenli Denklem

* 5 * x0 + x1 = 12
* x0 + 3 * x1 = 10

In [62]:
# Numpy'ın lineercebir alanına yönelik olarak içerisinde geliştirilmiş olan bir alt kütüphanesi var.
# linalg şeklinde bu kütüphaneyi kullanarak bu problemi çözebiliriz
# bu denklemlerdeki bu bilinmeyenlerin katsayılarını arrayler cinsinden ifade ederek Numpy'ına altında
# yer alan bir fonksiyon aracılığıyla bilinmeyen değerleri çözmüş olucaz.
# Öcelikle buradaki matematiksel ifadeyi numpy ın, python un anlayabileceği bir formata getirmemiz gerekiyor,
# bunun yoluda bilinmeyen ifadelerin katsayılarını bir vektöre koymak, bunun sonucunda oluşan değerleri
# bir vektöre koymak ve solve isimli fonksiyonu kullanarak bunları çözmek

In [48]:
# bilinmeyenlerin katsayıları
a = np.array([[5,1], [1,3]])
# bu bilinmeyenler sonucunda oluşan değerleride bir vektöre koyduk
b = np.array([12, 10])

In [49]:
a

array([[5, 1],
       [1, 3]])

In [50]:
b

array([12, 10])

* numpyın içerisinden lineercebir işlemleri için özelleştirilmiş alt paket içerisinden solve isimli bir fonksiyonu çağırıyorum 
* Diyoruzki; sen girmiş olduğum 1. argüman ve 2.argüman arasındaki ilişki neticesinde bu oluşacak olan katsayıları hesapla
* **x = np.linalg.solve(a, b)**

In [53]:
x = np.linalg.solve(a, b) 
x

array([1.85714286, 2.71428571])